# Generated by Django 4.0 on 2022-02-05 11:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0003_projectcodes_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcodes',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
