# Generated by Django 4.0 on 2022-02-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0005_remove_projectcodes_code_remove_projectcodes_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projectcodes',
        ),
    ]
