# Generated by Django 4.0 on 2022-02-05 12:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0007_projectcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcodes',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
