# Generated by Django 4.0 on 2022-02-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0008_projectcodes_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcodes',
            name='code',
        ),
    ]
