# Generated by Django 4.0 on 2022-02-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0010_projectvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideos',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
