# Generated by Django 4.0 on 2022-02-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0011_projectvideos_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projectvideos',
            new_name='myprojectvideos',
        ),
    ]
