# Generated by Django 4.0 on 2022-02-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0012_rename_projectvideos_myprojectvideos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myprojectvideos',
        ),
    ]
