# Generated by Django 4.0 on 2022-02-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0014_videosmyproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='myteamimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/MyTeam')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
