# Generated by Django 4.0 on 2022-01-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blog_post',
        ),
    ]
