# Generated by Django 4.0 on 2022-01-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_blog_blog_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_post',
            new_name='myblog',
        ),
    ]
