# Generated by Django 4.0 on 2022-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_blog_post_myblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='myportfilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('donefor', models.CharField(blank=True, max_length=255, null=True)),
                ('langauges', models.CharField(blank=True, max_length=255, null=True)),
                ('preview', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/image')),
            ],
        ),
    ]
