# Generated by Django 4.0 on 2022-01-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_myportfilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
