# Generated by Django 4.0 on 2022-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_myblog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/image'),
        ),
    ]
