# Generated by Django 4.0 on 2022-01-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_contactus_contactenquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactenquiry',
            new_name='contactus',
        ),
    ]
