# Generated by Django 4.0 on 2022-01-20 12:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_contactenquiry_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfilio',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='project', unique=True),
        ),
    ]
