# Generated by Django 4.0 on 2022-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_myportfilio_new_slug_myblog_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
