# Generated by Django 4.0 on 2022-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_myblog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='myskillsabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
