# Generated by Django 4.0 on 2022-02-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_mypersonalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mypersonalinfo',
        ),
    ]
