# Generated by Django 4.0 on 2022-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_myprofilepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myprofilepic',
        ),
        migrations.AddField(
            model_name='myskillsabout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
    ]
