# Generated by Django 4.0 on 2022-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_myskillsabout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='myprofilepic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/profile')),
            ],
        ),
    ]
